#!/bin/bash

cat <<'EOF' > /opt/intersystems/src/services/src/ICO/Test.cls
Class ICO.Test
{

ClassMethod QueryDB() As %Status
{
  set sqlquery = "SELECT * FROM ICO.inventory"
  set rs = ##class(%SQL.Statement).%ExecDirect(,sqlquery)
  while rs.%Next() {
    Write !, rs.%Get("vendor_id")
  }
}

}
EOF
