#!/bin/bash

su - irisowner <<EOSU
cat <<EOF | iris session iris -UUSER

set sql = "SELECT vendor_id,vendor_product_code,quantity_kg, date_arrival FROM ICO.inventory"
set msg = "Table ICO.inventory does not exist"
do ##class(%zInstruqt.Check).CheckSQLExec(sql, msg, .errors)

set sql = "SELECT catalog_id, product_code, quantity, price, time_roasted, roasting_notes, img FROM ICO.catalog"
set msg = "Table ICO.catalog does not exist"
do ##class(%zInstruqt.Check).CheckSQLExec(sql, msg, .errors)

do ##class(%zInstruqt.Check).Failure(.errors)
halt
EOF
EOSU

exit=$?

exit $exit
